version: '3'
services:
  mqtt:
    container_name: mqtt
    networks:
      - proxy
      - macvlan-mqtt
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker_storage/mosquitto:/mosquitto
    command: mosquitto -c /mosquitto/config/mosquitto.conf
  zigbee2mqtt:
    container_name: zigbee2mqtt
    networks:
      - proxy
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.local.raykain.com`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=https"
      - "traefik.http.routers.zigbee2mqtt.tls=true"
      - "traefik.http.services.zigbee2mqtt.loadBalancer.server.port=8080"
      - "traefik.http.routers.zigbee2mqtt.middlewares=http-https-redirect@file"
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker_storage/zigbee2mqtt:/app/data
      - /docker_storage/zigbee2mqtt/config:/app/data/config
networks:
  proxy:
    external: true
  macvlan-mqtt:
    external: true
